#!/bin/sh
# 5.10.0d-4 i686-debug-cygwin

## stages: 
make_debug=1
# cpan check all newer modules, needs manual update of the version list then
stage_cpan=
stage_vendorprep=
# delete buildperl, unpack src and apply patches
stage_prep=
stage_configure=1
stage_make=1
stage_check=1
stage_install=1
stage_installvendor=1
stage_pkg=1

prefix=/usr
pkg=perl
#ver=5.10.0d
shortver=5.10
longver=5.10.0
pkg_ver=${pkg}-${longver}
release=-4
major=5
minor=10
# shortver=`echo ${ver}${release} | sed 's/-.*//'`
usethreads="yes"
archname="i686-debug-cygwin"
exesuffix="d"
ver="${longver}${exesuffix}"

dir=`pwd`
srcdir=${dir}/${pkg_ver}
builddir=${dir}/builddebug
instdir=${dir}/instdebug

source build_common
source modules

#stage_cpan
stage_vendorprep
stage_prep
stage_configure_policy() {
  __substage "configure_policy"
  echo "otherlibdirs='/usr/lib/perl5/site_perl/5.8'" >> $builddir/Policy.sh
}
stage_configure

# patch dllname in cygwin/Makefile.SHs
#rm cygwin/Makefile.SHs
#sed -e's,dllname="${dllname}"d,dllname="${dllname}"d-nt,' < ${srcdir}/cygwin/Makefile.SHs > cygwin/Makefile.SHs

stage_make
stage_check

__stage_post_install_hook() {
    __substage "post_install_hook"
    if [ ! -e $instdir/usr/lib/perl5/$shortver/$archname/auto/Win32CORE/Win32CORE.a ]
    then
	cp $buildir/lib/auto/Win32CORE/Win32CORE.a $instdir/usr/lib/perl5/$shortver/$archname/auto/Win32CORE/Win32CORE.a
    fi
}
stage_install
stage_installvendor

# before packing. add the special buildscript. in ${dir}
stage_spkg_hook() {
    echo "## stage_spkg_hook"
    cp build-debug ${pkg}-${ver}${release}/
}
# additional to the perl package: just the archlibs and executables. in ${instdir}
stage_pkg_hook() {
    echo "## stage_pkg_hook"
    # rename the perl and a2p exe
    mv usr/bin/perl${longver}.exe usr/bin/perl${ver}.exe
    mv usr/bin/a2p${longver}.exe usr/bin/a2p${ver}.exe
    find usr/bin/*.exe usr/bin/*.dll usr/lib/ usr/share/doc -type f -print > ${files}.perl
    echo usr/lib/perl5/${shortver}/${archname} >>${files}.perl
    echo usr/lib/perl5/vendor_perl/${shortver}/${archname} >>${files}.perl
}

stage_pkg
