#!/bin/sh
# 5.10.1-3 i686-cygwin

## stages: 
make_debug=
# cpan checks externally all newer modules, needs manual update of the version list then
stage_cpan=
# check if all required modules exist
stage_vendorprep=
# delete buildperl, unpack src and apply patches
stage_prep=
stage_configure=0
stage_make=1
stage_check=1
stage_install=1
stage_installvendor=
stage_pkg=

prefix=/usr
pkg=perl

ver=5.10.1
release=-3
pkg_ver=perl-5.10.1
shortver=5.10
subversion=1
major=5
minor=10
longver=${ver}
usethreads=yes
#archname="i686-cygwin"
download_url="http://search.cpan.org/CPAN/authors/id/D/DA/DAPM/perl-5.10.1.tar.gz"
rsync_url="rsync://ftp.linux.activestate.com/perl-5.10.x/"

dir=`pwd`
srcdir=${dir}/${pkg_ver}

source build_common
source modules

stage_cpan
stage_vendorprep
stage_prep
stage_configure_policy() {
  echo "otherlibdirs='/usr/lib/perl5/site_perl/5.8:/usr/lib/perl5/vendor_perl/5.8'" >> Policy.sh
}
stage_configure
stage_make
stage_check
stage_install
stage_installvendor
stage_pkg
